stages:
  data_load:
    cmd: dvc pull AirQuality.csv
    outs: AirQuality.csv

  data_prep:
    cmd: python3 data_load.py
    deps:
    - data_load.py
    - AirQuality.csv
    outs:
    - prepared_data.csv
  prepare_and_train:
    cmd: python3 prepare_and_train.py
    deps:
      - prepare_and_train.py
      - prepared_data.csv
    metrics:
      - metrics.json:
          cache: false